/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.form;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author daylton
 */
public class FormCliente extends javax.swing.JFrame {

    /**
     * Creates new form FrmHash
     */
    
    int player;
    int cont; // verificar se dará velha
    
    public FormCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        player = 1;
        cont = 0;
    }
    
    
    public void jogada(){
        
        if (btn1.getText().equals("X") && btn2.getText().equals("X") && btn3.getText().equals("X")){
            JOptionPane.showMessageDialog(null, "Jogador 1 VENCEU!!!!!!!!");             
        }
        if (btn4.getText().equals("X") && btn5.getText().equals("X") && btn6.getText().equals("X")){
            JOptionPane.showMessageDialog(null, "Jogador 1 VENCEU!!!!!!!!");
        }
        if (btn7.getText().equals("X") && btn8.getText().equals("X") && btn9.getText().equals("X")){
             JOptionPane.showMessageDialog(null, "Jogador 1 VENCEU!!!!!!!!");
        }
        if (btn1.getText().equals("X") && btn4.getText().equals("X") && btn7.getText().equals("X")){
             JOptionPane.showMessageDialog(null, "Jogador 1 VENCEU!!!!!!!!");
        }
        if (btn2.getText().equals("X") && btn5.getText().equals("X") && btn8.getText().equals("X")){
            JOptionPane.showMessageDialog(null, "Jogador 1 VENCEU!!!!!!!!");
        }
        if (btn3.getText().equals("X") && btn6.getText().equals("X") && btn9.getText().equals("X")){
            JOptionPane.showMessageDialog(null, "Jogador 1 VENCEU!!!!!!!!");
        }
        if (btn1.getText().equals("X") && btn5.getText().equals("X") && btn9.getText().equals("X")){
            JOptionPane.showMessageDialog(null, "Jogador 1 VENCEU!!!!!!!!");
        }
        if (btn3.getText().equals("X") && btn5.getText().equals("X") && btn7.getText().equals("X")){        
            JOptionPane.showMessageDialog(null, "Jogador 1 VENCEU!!!!!!!!");
        }

        if (btn1.getText().equals("O") && btn2.getText().equals("O") && btn3.getText().equals("O")){
            JOptionPane.showMessageDialog(null, "Jogador 2 VENCEU!!!!!!!!");
        }
        if (btn4.getText().equals("O") && btn5.getText().equals("O") && btn6.getText().equals("O")){
            JOptionPane.showMessageDialog(null, "Jogador 2 VENCEU!!!!!!!!");
        }
        if (btn7.getText().equals("O") && btn8.getText().equals("O") && btn9.getText().equals("O")){
             JOptionPane.showMessageDialog(null, "Jogador 2 VENCEU!!!!!!!!");
        }
        if (btn1.getText().equals("O") && btn4.getText().equals("O") && btn7.getText().equals("O")){
             JOptionPane.showMessageDialog(null, "Jogador 2 VENCEU!!!!!!!!");
        }
        if (btn2.getText().equals("O") && btn5.getText().equals("O") && btn8.getText().equals("O")){
            JOptionPane.showMessageDialog(null, "Jogador 2 VENCEU!!!!!!!!");
        }
        if (btn3.getText().equals("O") && btn6.getText().equals("O") && btn9.getText().equals("O")){
            JOptionPane.showMessageDialog(null, "Jogador 2 VENCEU!!!!!!!!");
        }
        if (btn1.getText().equals("O") && btn5.getText().equals("O") && btn9.getText().equals("O")){
            JOptionPane.showMessageDialog(null, "Jogador 2 VENCEU!!!!!!!!");
        }
        if (btn3.getText().equals("O") && btn5.getText().equals("O") && btn7.getText().equals("O")){        
            JOptionPane.showMessageDialog(null, "Jogador 2 VENCEU!!!!!!!!");
        }

        if(cont == 9){
            JOptionPane.showMessageDialog(null, "VELHA!!!!!!!!!!!!!!!");
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnStart.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        btnStart.setForeground(new java.awt.Color(0, 255, 0));
        btnStart.setText("INICIAR");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnStart)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        switch(player){
            case 1:
                btn1.setText("X");
                btn1.setForeground(Color.RED);
                player = 2;
                jogada();
                break;
            case 2:
                btn1.setText("O");
                btn1.setForeground(Color.BLUE);
                player = 1;
                jogada();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        switch(player){
            case 1:
                btn2.setText("X");
                btn2.setForeground(Color.RED);
                player = 2;
                jogada();
                break;
            case 2:
                btn2.setText("O");
                btn2.setForeground(Color.BLUE);
                player = 1;
                jogada();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        switch(player){
            case 1:
                btn3.setText("X");
                btn3.setForeground(Color.RED);
                player = 2;
                jogada();
                break;
            case 2:
                btn3.setText("O");
                btn3.setForeground(Color.BLUE);
                player = 1;
                jogada();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        switch(player){
            case 1:
                btn4.setText("X");
                btn4.setForeground(Color.RED);
                player = 2;
                jogada();
                break;
            case 2:
                btn4.setText("O");
                btn4.setForeground(Color.BLUE);
                player = 1;
                jogada();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        switch(player){
            case 1:
                btn5.setText("X");
                btn5.setForeground(Color.RED);
                player = 2;
                jogada();
                break;
            case 2:
                btn5.setText("O");
                btn5.setForeground(Color.BLUE);
                player = 1;
                jogada();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        switch(player){
            case 1:
                btn6.setText("X");
                btn6.setForeground(Color.RED);
                player = 2;
                jogada();
                break;
            case 2:
                btn6.setText("O");
                btn6.setForeground(Color.BLUE);
                player = 1;
                jogada();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        switch(player){
            case 1:
                btn7.setText("X");
                btn7.setForeground(Color.RED);
                player = 2;
                jogada();
                break;
            case 2:
                btn7.setText("O");
                btn7.setForeground(Color.BLUE);
                player = 1;
                jogada();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        switch(player){
            case 1:
                btn8.setText("X");
                btn8.setForeground(Color.RED);
                player = 2;
                jogada();
                break;
            case 2:
                btn8.setText("O");
                btn8.setForeground(Color.BLUE);
                player = 1;
                
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        switch(player){
            case 1:
                btn9.setText("X");
                btn9.setForeground(Color.RED);
                player = 2;
                jogada();
                break;
            case 2:
                btn9.setText("O");
                btn9.setForeground(Color.BLUE);
                player = 1;
                jogada();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        player = 1;
        cont = 0;
        btn1.setText("");
        btn2.setText("");
        btn3.setText("");
        btn4.setText("");
        btn5.setText("");
        btn6.setText("");
        btn7.setText("");
        btn8.setText("");
        btn9.setText("");
        
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnStart;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
